// Code generated by core/cmd/fsapis. DO NOT EDIT.
//
// A typed client over the same Go types the handlers are written against.
// Compiles for GOOS=js too, where net/http is the browser's fetch().

package apiclient

import (
	"context"
	"github.com/mirairoad/appeditions/client/store"
	"github.com/mirairoad/appeditions/internal/exporter"
	"github.com/mirairoad/appeditions/server/apis"
	"github.com/mirairoad/appeditions/server/apis/apistore"
	"github.com/mirairoad/appeditions/server/apis/projects"
	id_dyn "github.com/mirairoad/appeditions/server/apis/projects/id.dyn"
	"github.com/mirairoad/appeditions/server/apis/projects/id.dyn/ai"
	screen_id_dyn "github.com/mirairoad/appeditions/server/apis/projects/id.dyn/screens/screen_id.dyn"
	"github.com/mirairoad/howl-go/core/api"
)

// Client calls the API. An empty base URL means same origin, which is what
// a page running in the browser wants.
type Client struct{ *api.Transport }

func New(baseURL string) *Client { return &Client{Transport: api.NewTransport(baseURL)} }

// ApplyOp calls POST /api/projects/{id}/ops.
func (c *Client) ApplyOp(ctx context.Context, id string, body store.Op) (store.EditorSnapshot, error) {
	return api.Call[store.EditorSnapshot](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/ops", id), nil, body)
}

// ApplyRhythm calls POST /api/projects/{id}/rhythm.
func (c *Client) ApplyRhythm(ctx context.Context, id string, body id_dyn.RhythmChoice) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/rhythm", id), nil, body)
}

// ApplyTemplate calls POST /api/projects/{id}/template.
func (c *Client) ApplyTemplate(ctx context.Context, id string, body id_dyn.TemplateChoice) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/template", id), nil, body)
}

// ClearOverrides calls POST /api/projects/{id}/screens/{screen_id}/reset.
func (c *Client) ClearOverrides(ctx context.Context, id string, screenId string, body screen_id_dyn.Reset) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/screens/{screen_id}/reset", id, screenId), nil, body)
}

// CreateProject calls POST /api/projects.
func (c *Client) CreateProject(ctx context.Context, body projects.New) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", "/api/projects", nil, body)
}

// DeleteAsset calls POST /api/projects/{id}/assets/{asset_id}/delete.
func (c *Client) DeleteAsset(ctx context.Context, id string, assetId string) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/assets/{asset_id}/delete", id, assetId), nil, nil)
}

// DeleteProject calls POST /api/projects/{id}/delete.
func (c *Client) DeleteProject(ctx context.Context, id string) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/delete", id), nil, nil)
}

// DeleteTemplate calls POST /api/templates/{id}/delete.
func (c *Client) DeleteTemplate(ctx context.Context, id string) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/templates/{id}/delete", id), nil, nil)
}

// DeleteVersion calls POST /api/projects/{id}/version-delete.
func (c *Client) DeleteVersion(ctx context.Context, id string, body id_dyn.VersionRef) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/version-delete", id), nil, body)
}

// DuplicateTemplate calls POST /api/templates/{id}/duplicate.
func (c *Client) DuplicateTemplate(ctx context.Context, id string) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/templates/{id}/duplicate", id), nil, nil)
}

// EditorSnapshot calls GET /api/projects/{id}/snapshot.
func (c *Client) EditorSnapshot(ctx context.Context, id string) (store.EditorSnapshot, error) {
	return api.Call[store.EditorSnapshot](ctx, c.Transport, "GET", api.Path("/api/projects/{id}/snapshot", id), nil, nil)
}

// Export calls POST /api/projects/{id}/export.
func (c *Client) Export(ctx context.Context, id string, body id_dyn.ExportRequest) (exporter.Result, error) {
	return api.Call[exporter.Result](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/export", id), nil, body)
}

// MoveScreen calls POST /api/projects/{id}/screens/{screen_id}/move.
func (c *Client) MoveScreen(ctx context.Context, id string, screenId string, body screen_id_dyn.Move) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/screens/{screen_id}/move", id, screenId), nil, body)
}

// NewVersion calls POST /api/projects/{id}/versions.
func (c *Client) NewVersion(ctx context.Context, id string, body id_dyn.Release) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/versions", id), nil, body)
}

// PinSetting calls POST /api/projects/{id}/screens/{screen_id}/settings.
func (c *Client) PinSetting(ctx context.Context, id string, screenId string, body apistore.Setting) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/screens/{screen_id}/settings", id, screenId), nil, body)
}

// RemoveScreen calls POST /api/projects/{id}/screens/{screen_id}/remove.
func (c *Client) RemoveScreen(ctx context.Context, id string, screenId string) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/screens/{screen_id}/remove", id, screenId), nil, nil)
}

// Reveal calls POST /api/reveal.
func (c *Client) Reveal(ctx context.Context, body apis.Target) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", "/api/reveal", nil, body)
}

// SaveRelease calls POST /api/projects/{id}/release.
func (c *Client) SaveRelease(ctx context.Context, id string, body id_dyn.Release) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/release", id), nil, body)
}

// SaveTemplate calls POST /api/projects/{id}/save-template.
func (c *Client) SaveTemplate(ctx context.Context, id string, body id_dyn.TemplateDraft) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/save-template", id), nil, body)
}

// SetCopy calls POST /api/projects/{id}/screens/{screen_id}/copy.
func (c *Client) SetCopy(ctx context.Context, id string, screenId string, body screen_id_dyn.CopyEdit) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/screens/{screen_id}/copy", id, screenId), nil, body)
}

// SetLocales calls POST /api/projects/{id}/locales.
func (c *Client) SetLocales(ctx context.Context, id string, body id_dyn.LocaleChange) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/locales", id), nil, body)
}

// SetPicture calls POST /api/projects/{id}/screens/{screen_id}/picture.
func (c *Client) SetPicture(ctx context.Context, id string, screenId string, body screen_id_dyn.Pick) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/screens/{screen_id}/picture", id, screenId), nil, body)
}

// SetSetting calls POST /api/projects/{id}/settings.
func (c *Client) SetSetting(ctx context.Context, id string, body apistore.Setting) (apistore.Saved, error) {
	return api.Call[apistore.Saved](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/settings", id), nil, body)
}

// TranslateCopy calls POST /api/projects/{id}/ai/translate.
func (c *Client) TranslateCopy(ctx context.Context, id string, body ai.TranslateRequest) (ai.Drafted, error) {
	return api.Call[ai.Drafted](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/ai/translate", id), nil, body)
}

// WriteCopy calls POST /api/projects/{id}/ai/write.
func (c *Client) WriteCopy(ctx context.Context, id string, body ai.Draft) (ai.Drafted, error) {
	return api.Call[ai.Drafted](ctx, c.Transport, "POST", api.Path("/api/projects/{id}/ai/write", id), nil, body)
}
