// Code generated by tools/fsroutes. DO NOT EDIT.
// Source of truth is the directory tree under client/pages.

package pages

import (
	p1 "github.com/mirairoad/appeditions/client/pages/projects/id.dyn"
	p2 "github.com/mirairoad/appeditions/client/pages/projects/id.dyn/copy"
	p3 "github.com/mirairoad/appeditions/client/pages/projects/id.dyn/export"
	p4 "github.com/mirairoad/appeditions/client/pages/projects/id.dyn/look"
	p5 "github.com/mirairoad/appeditions/client/pages/projects/id.dyn/tune"
	p0 "github.com/mirairoad/appeditions/client/pages/templates"
	"github.com/mirairoad/howl-go/core/router"
)

// FsClientRoutes is the route table derived from the page tree.
func FsClientRoutes() []router.Route {
	return []router.Route{
		{Pattern: "/", Label: "Home", Page: Index, Head: Head, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{Layout}, Client: false, Raw: false},
		{Pattern: "/templates", Label: "Templates", Page: p0.Templates, Head: p0.Head, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{Layout}, Client: false, Raw: false},
		{Pattern: "/projects/{id}", Label: "Id", Page: p1.Release, Head: p1.Head, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{Layout, p1.Layout}, Client: false, Raw: false},
		{Pattern: "/projects/{id}/copy", Label: "Copy", Page: p2.Copy, Head: p2.Head, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{Layout, p1.Layout}, Client: false, Raw: false},
		{Pattern: "/projects/{id}/export", Label: "Export", Page: p3.Export, Head: p3.Head, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{Layout, p1.Layout}, Client: false, Raw: false},
		{Pattern: "/projects/{id}/look", Label: "Look", Page: p4.Look, Head: p4.Head, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{Layout, p1.Layout}, Client: false, Raw: false},
		{Pattern: "/projects/{id}/tune", Label: "Tune", Page: p5.Tune, Head: p5.Head, Mount: nil, Unmount: nil, Layouts: []router.Wrapper{Layout, p1.Layout}, Client: false, Raw: false},
	}
}
