// Code generated by core/cmd/fsapis. DO NOT EDIT.
// Source of truth is the directory tree under server/apis.

package apis

import (
	e0 "github.com/mirairoad/appeditions/server/apis/projects"
	e3 "github.com/mirairoad/appeditions/server/apis/projects/id.dyn"
	e1 "github.com/mirairoad/appeditions/server/apis/projects/id.dyn/ai"
	e2 "github.com/mirairoad/appeditions/server/apis/projects/id.dyn/assets/asset_id.dyn"
	e4 "github.com/mirairoad/appeditions/server/apis/projects/id.dyn/screens/screen_id.dyn"
	e5 "github.com/mirairoad/appeditions/server/apis/templates/id.dyn"
	"github.com/mirairoad/howl-go/core/api"
)

// FsApiRoutes is the endpoint table derived from the file tree.
// Pass it to api.Register together with the application's api.Config.
func FsApiRoutes() []api.Route {
	return []api.Route{
		api.At("POST", "/api/projects", e0.Create),
		api.At("POST", "/api/projects/{id}/ai/translate", e1.Translate),
		api.At("POST", "/api/projects/{id}/ai/write", e1.Write),
		api.At("POST", "/api/projects/{id}/assets/{asset_id}/delete", e2.DeleteAsset),
		api.At("POST", "/api/projects/{id}/delete", e3.Delete),
		api.At("POST", "/api/projects/{id}/export", e3.Export),
		api.At("POST", "/api/projects/{id}/locales", e3.SetLocales),
		api.At("POST", "/api/projects/{id}/ops", e3.Ops),
		api.At("POST", "/api/projects/{id}/release", e3.SaveRelease),
		api.At("POST", "/api/projects/{id}/rhythm", e3.ApplyRhythm),
		api.At("POST", "/api/projects/{id}/save-template", e3.SaveTemplate),
		api.At("POST", "/api/projects/{id}/screens/{screen_id}/copy", e4.SetCopy),
		api.At("POST", "/api/projects/{id}/screens/{screen_id}/move", e4.MoveScreen),
		api.At("POST", "/api/projects/{id}/screens/{screen_id}/picture", e4.SetPicture),
		api.At("POST", "/api/projects/{id}/screens/{screen_id}/remove", e4.RemoveScreen),
		api.At("POST", "/api/projects/{id}/screens/{screen_id}/reset", e4.ClearOverrides),
		api.At("POST", "/api/projects/{id}/screens/{screen_id}/settings", e4.PinSetting),
		api.At("POST", "/api/projects/{id}/settings", e3.SetSetting),
		api.At("GET", "/api/projects/{id}/snapshot", e3.Snapshot),
		api.At("POST", "/api/projects/{id}/template", e3.ApplyTemplate),
		api.At("POST", "/api/projects/{id}/version-delete", e3.DeleteVersion),
		api.At("POST", "/api/projects/{id}/versions", e3.NewVersion),
		api.At("POST", "/api/reveal", Reveal),
		api.At("POST", "/api/templates/{id}/delete", e5.Delete),
		api.At("POST", "/api/templates/{id}/duplicate", e5.Duplicate),
		api.At("POST", "/api/update", Update),
	}
}
